export function createState() {
  return {
    currentRow: null,
    currentRowIdentity: null,
    lastBlur: null,
    blurPlaybackTime: null,
    restorePlaybackTime: null,
    blurRestorePending: false,
    runtimeBound: false,
    routeWatchBound: false,
    routeRefreshTimer: 0,
    routeRefreshAttempts: 0,
    routeRefreshWindowStartedAt: 0,
    hotkeysEnhanceFrame: 0,
    hotkeysObserver: null,
    routeRecoveryObserver: null,
    keydownBound: false,
    nativeArrowSuppressBound: false,
    sessionActive: false,
    rowTrackingBound: false,
    cutListenersBound: false,
    magnifierListenersBound: false,
    cutDraft: null,
    cutPreview: null,
    cutCommitPending: false,
    cutLastContainer: null,
    smartSplitClickDraft: null,
    smartSplitClickContext: null,
    selectionLoop: null,
    magnifier: null,
    magnifierDrag: null,
    speakerSwitchPending: false,
    cursorBaseline: null,
    ghostCursorElement: null,
    ghostCursorIntervalId: null,
    ghostCursorRow: null,
    ghostCursorRowIdentity: null,
    ghostCursorOffset: null,
    playbackRowSyncTimer: null,
    playbackRowSyncInFlight: false,
    lastPlaybackRow: null,
    lastPlaybackRowIdentity: null
  };
}

